version: '3.4'

services:

  klipper:
    image: klipper:latest
    build:
      args:
        VERSION: 319c36df52eb016667d13ab006cae3752d0212e7
      dockerfile: klipper.Dockerfile
      context: .
      target: klippy
    container_name: klipper
    restart: unless-stopped
    volumes:
      - ./config:/opt/cfg
      - run:/opt/run
      - gcode:/opt/gcode
    devices:
      - /dev/ttymxc3:/dev/ttymxc3

  moonraker:
    image: moonraker:latest
    build:
      dockerfile: moonraker.Dockerfile
      context: .
    container_name: moonraker
    restart: unless-stopped
    volumes:
      - ./config:/opt/cfg
      - run:/opt/run
      - gcode:/opt/gcode
      - db:/opt/db
    ports:
      - 7125:7125

  fluidd:
    image: cadriel/fluidd:latest
    container_name: fluidd
    restart: unless-stopped
    ports:
      - 80:80

volumes:
  run:
  gcode:
  db:
