name: build-images
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run Build Script
        run: bash ./scripts/build-images.sh ${{ secrets.DOCKERHUB_USERNAME }}/
